name: 'Update schedule'

on:
  workflow_dispatch:
  schedule:
    # 每天北京时间 06:30 (UTC 22:30) 定时执行更新
    - cron: '30 22 * * *'

permissions:
  contents: write

jobs:
  push:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
    steps:
      - name: Set branch name
        id: vars
        run: echo "BRANCH_NAME=${{ github.repository_owner == 'Guovin' && 'gd' || github.ref_name || 'master' }}" >> $GITHUB_ENV
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Run with setup-python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          update-environment: true
          cache: 'pipenv'
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install pipenv
        run: pip3 install --user pipenv
      - name: Install dependencies
        run: pipenv --python 3.14 && (pipenv install --deploy || pipenv install)
      - name: Update
        run: pipenv run dev
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Github Action Auto Updated [skip ci]"
            git pull --rebase origin ${{ env.BRANCH_NAME }} || true
            git push origin ${{ env.BRANCH_NAME }}
          else
            echo "No changes detected, skipping commit."
          fi
